version: '3.3'
services:
    {{APP_NAME}}:
        container_name: "{{APP_NAME}}_dev"
        image: "{{APP_NAME}}_image_dev"
        build:
            context: .
            dockerfile: ./docker_files/Dockerfile.compose
            args:
                MIX_ENV: dev
        working_dir: /application/{{APP_NAME}}_umbrella
        ports:
            - "4000:4000"
        volumes:
            - .:/application
        environment:
            MIX_ENV: dev
            PORT: 4000
            POSTGRES_HOSTNAME: postgres_{{APP_NAME}}
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: supersecret
            POSTGRES_DATABASE: postgres_{{APP_NAME}}
            SECRET_KEY_BASE_ENDPOINT: {{SECRET_KEY}}_{{APP_NAME}}
        depends_on:
            - postgres_{{APP_NAME}}
        command: /bin/bash /application/docker_files/docker_command.sh

    postgres_{{APP_NAME}}:
        image: postgres:9.6
        container_name: "{{APP_NAME}}_postgres_dev"
        ports:
            - "11223:5432"
        environment:
            POSTGRES_PASSWORD: supersecret
