FROM weareyipyip/elixir-sass:1.6.2
LABEL maintainer "YipYip <devops@yipyip.nl>"

ARG MIX_ENV
ENV MIX_ENV=$MIX_ENV

ADD . /application
WORKDIR /application/{{APP_NAME}}_umbrella

RUN mix local.hex --force
RUN mix local.rebar --force

CMD ["mix", "phx.server"]
